GET https://qu1zmf2c2l.execute-api.us-east-1.amazonaws.com/prod/spaces
###

POST https://qu1zmf2c2l.execute-api.us-east-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
  "location": "Dublin",
  "name": "Best location"
}
###

GET https://qu1zmf2c2l.execute-api.us-east-1.amazonaws.com/prod/spaces?id=d3be28ed-4f87-4e3d-999b-bfa9141608e3
###

DELETE https://qu1zmf2c2l.execute-api.us-east-1.amazonaws.com/prod/spaces?id=d3be28ed-4f87-4e3d-999b-bfa9141608e3
###

PUT https://qu1zmf2c2l.execute-api.us-east-1.amazonaws.com/prod/spaces?id=d3be28ed-4f87-4e3d-999b-bfa9141608e3
Content-Type: application/json

{
  "name": "Best location 2"
}
###
