@baseUrl = https://6np67n3288.execute-api.us-east-1.amazonaws.com/prod/

GET {{baseUrl}}/spaces
###

# @name postSpace
POST {{baseUrl}}/spaces
Content-Type: application/json

{
  "location": "Dublin",
  "name": "Best location"
}
###

@spaceId = {{postSpace.response.body.id}}

GET {{baseUrl}}/spaces?id={{spaceId}}
###

DELETE {{baseUrl}}/spaces?id={{spaceId}}
###

PUT {{baseUrl}}/spaces?id={{spaceId}}
Content-Type: application/json

{
  "name": "Best location 2"
}
###
