GET https://qu1zmf2c2l.execute-api.us-east-1.amazonaws.com/prod/spaces
###

POST https://qu1zmf2c2l.execute-api.us-east-1.amazonaws.com/prod/spaces
Content-Type: application/json

{
  "location": "Dublin",
  "name": "Best location"
}
###

GET https://qu1zmf2c2l.execute-api.us-east-1.amazonaws.com/prod/spaces?id=798fb57f-c942-4bcb-be63-43782c68afc2
###

DELETE https://qu1zmf2c2l.execute-api.us-east-1.amazonaws.com/prod/spaces?id=798fb57f-c942-4bcb-be63-43782c68afc2
###

PUT https://qu1zmf2c2l.execute-api.us-east-1.amazonaws.com/prod/spaces?id=798fb57f-c942-4bcb-be63-43782c68afc2
Content-Type: application/json

{
  "name": "Best location 2"
}
###
